backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

site_url: https:/gabriele.pallaoro.dev
display_url: https:/gabriele.pallaoro.dev

collections:
  - name: blog
    label: Blog
    folder: blog
    slug: "{{year}}-{{month}}-{{slug}}"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: list }
      - { name: title, label: Title }
      - { name: online, label: Visible, widget: boolean }
      - { name: body, label: Body, widget: markdown }
